# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_frustumR_wrappers", use_symbols = TRUE, package_name = "frustumR")

#' @docType package
#' @usage NULL
#' @useDynLib frustumR, .registration = TRUE
NULL

#' Create a perspective camera
#' @param position Camera position as c(x, y, z)
#' @param target Look-at target as c(x, y, z)
#' @param fov_degrees Field of view in degrees
#' @return External pointer to Camera object
#' @export
camera_perspective <- function(position, target, fov_degrees) {
  .Call(wrap__camera_perspective, position, target, fov_degrees)
}

#' Create an orthographic camera
#' @param position Camera position as c(x, y, z)
#' @param target Look-at target as c(x, y, z)
#' @param scale Orthographic scale factor
#' @return External pointer to Camera object
#' @export
camera_orthographic <- function(position, target, scale) {
  .Call(wrap__camera_orthographic, position, target, scale)
}

#' Create a directional light
#' @param direction Light direction as c(x, y, z)
#' @param intensity Light intensity (0-1)
#' @return External pointer to Light object
#' @export
light_new <- function(direction, intensity) {
  .Call(wrap__light_new, direction, intensity)
}

#' Scientific flat lighting preset
#' @return External pointer to Light object
#' @export
light_scientific_flat <- function() .Call(wrap__light_scientific_flat)

#' Studio soft lighting preset
#' @return External pointer to Light object
#' @export
light_studio_soft <- function() .Call(wrap__light_studio_soft)

#' Rim highlight lighting preset
#' @return External pointer to Light object
#' @export
light_rim_highlight <- function() .Call(wrap__light_rim_highlight)

#' Depth emphasis lighting preset
#' @return External pointer to Light object
#' @export
light_depth_emphasis <- function() .Call(wrap__light_depth_emphasis)

#' Side light lighting preset
#' @return External pointer to Light object
#' @export
light_side_light <- function() .Call(wrap__light_side_light)

#' Three-quarter lighting preset (classic)
#' @return External pointer to Light object
#' @export
light_three_quarter <- function() .Call(wrap__light_three_quarter)

#' Create a solid color material
#' @param id Material identifier string
#' @param color RGB color as c(r, g, b) with values in [0, 1]
#' @return External pointer to Material object
#' @export
material_solid <- function(id, color) {
  .Call(wrap__material_solid, id, color)
}

#' Create a solid color material with alpha
#' @param id Material identifier string
#' @param color RGBA color as c(r, g, b, a) with values in [0, 1]
#' @return External pointer to Material object
#' @export
material_solid_alpha <- function(id, color) {
  .Call(wrap__material_solid_alpha, id, color)
}

#' Create a scalar-mapped colormap material
#' @param id Material identifier string
#' @param colormap Colormap name ("viridis", "plasma", "magma", "inferno", "cividis")
#' @param range Scalar range as c(min, max)
#' @return External pointer to Material object
#' @export
material_scalar_mapped <- function(id, colormap, range) {
  .Call(wrap__material_scalar_mapped, id, colormap, range)
}

#' Create a mesh from positions and indices
#' @param positions Flat vector of vertex positions (x0,y0,z0, x1,y1,z1, ...)
#' @param indices Flat vector of triangle indices (i0,i1,i2, ...)
#' @return External pointer to Mesh object
#' @export
mesh_new <- function(positions, indices) {
  .Call(wrap__mesh_new, positions, as.integer(indices))
}

#' Set material ID on a mesh
#' @param mesh External pointer to Mesh
#' @param material_id Material identifier string
#' @return External pointer to new Mesh with material
#' @export
mesh_with_material <- function(mesh, material_id) {
  .Call(wrap__mesh_with_material, mesh, material_id)
}

#' Set normals on a mesh
#' @param mesh External pointer to Mesh
#' @param normals Flat vector of vertex normals
#' @return External pointer to new Mesh with normals
#' @export
mesh_with_normals <- function(mesh, normals) {
  .Call(wrap__mesh_with_normals, mesh, normals)
}

#' Set scalars on a mesh (for colormap materials)
#' @param mesh External pointer to Mesh
#' @param scalars Vector of per-vertex scalar values
#' @return External pointer to new Mesh with scalars
#' @export
mesh_with_scalars <- function(mesh, scalars) {
  .Call(wrap__mesh_with_scalars, mesh, scalars)
}

#' Get triangle count from mesh
#' @param mesh External pointer to Mesh
#' @return Number of triangles
#' @export
mesh_triangle_count <- function(mesh) {
  .Call(wrap__mesh_triangle_count, mesh)
}

#' Get vertex count from mesh
#' @param mesh External pointer to Mesh
#' @return Number of vertices
#' @export
mesh_vertex_count <- function(mesh) {
  .Call(wrap__mesh_vertex_count, mesh)
}

#' Create a point cloud
#' @param positions Flat vector of point positions (x0,y0,z0, x1,y1,z1, ...)
#' @param size Point size
#' @return External pointer to PointCloud object
#' @export
pointcloud_new <- function(positions, size) {
  .Call(wrap__pointcloud_new, positions, size)
}

#' Set material ID on a point cloud
#' @export
pointcloud_with_material <- function(pc, material_id) {
  .Call(wrap__pointcloud_with_material, pc, material_id)
}

#' Set scalars on a point cloud
#' @export
pointcloud_with_scalars <- function(pc, scalars) {
  .Call(wrap__pointcloud_with_scalars, pc, scalars)
}

#' Create a polyline
#' @param positions Flat vector of vertex positions
#' @param width Line width
#' @return External pointer to Polyline object
#' @export
polyline_new <- function(positions, width) {
  .Call(wrap__polyline_new, positions, width)
}

#' Set material ID on a polyline
#' @export
polyline_with_material <- function(line, material_id) {
  .Call(wrap__polyline_with_material, line, material_id)
}

#' Create a 3D volume from scalar values
#' @param values Flat vector of scalar values (row-major order: x varies fastest)
#' @param dimensions Volume dimensions as c(nx, ny, nz)
#' @param spacing Voxel spacing as c(dx, dy, dz)
#' @param origin Volume origin as c(ox, oy, oz)
#' @return External pointer to Volume object
#' @export
volume_new <- function(values, dimensions, spacing, origin) {
  .Call(wrap__volume_new, values, as.integer(dimensions), spacing, origin)
}

#' Get value range of a volume
#' @param volume External pointer to Volume
#' @return c(min, max) value range
#' @export
volume_value_range <- function(volume) {
  .Call(wrap__volume_value_range, volume)
}

#' Compute gradient magnitude of a volume
#' @param volume External pointer to Volume
#' @return External pointer to new Volume with gradient magnitude
#' @export
volume_gradient_magnitude <- function(volume) {
  .Call(wrap__volume_gradient_magnitude, volume)
}

#' Compute Laplacian of a volume
#' @param volume External pointer to Volume
#' @return External pointer to new Volume with Laplacian
#' @export
volume_laplacian <- function(volume) {
  .Call(wrap__volume_laplacian, volume)
}

#' Extract isosurface using marching cubes
#' @param volume External pointer to Volume
#' @param iso_value Isovalue for surface extraction
#' @return External pointer to Mesh
#' @export
marching_cubes <- function(volume, iso_value) {
  .Call(wrap__marching_cubes, volume, iso_value)
}

#' Extract multiple isosurfaces
#' @param volume External pointer to Volume
#' @param iso_values Vector of isovalues
#' @return List of Mesh external pointers
#' @export
marching_cubes_multi <- function(volume, iso_values) {
  .Call(wrap__marching_cubes_multi, volume, iso_values)
}

#' Create a new scene
#' @param camera External pointer to Camera
#' @param bounds_min Scene minimum bounds as c(x, y, z)
#' @param bounds_max Scene maximum bounds as c(x, y, z)
#' @return External pointer to Scene object
#' @export
scene_new <- function(camera, bounds_min, bounds_max) {
  .Call(wrap__scene_new, camera, bounds_min, bounds_max)
}

#' Add a mesh to the scene (returns new scene)
#' @export
scene_add_mesh <- function(scene, mesh) {
  .Call(wrap__scene_add_mesh, scene, mesh)
}

#' Add a point cloud to the scene (returns new scene)
#' @export
scene_add_points <- function(scene, points) {
  .Call(wrap__scene_add_points, scene, points)
}

#' Add a polyline to the scene (returns new scene)
#' @export
scene_add_polyline <- function(scene, polyline) {
  .Call(wrap__scene_add_polyline, scene, polyline)
}

#' Add a material to the scene (returns new scene)
#' @export
scene_add_material <- function(scene, material) {
  .Call(wrap__scene_add_material, scene, material)
}

#' Set the scene light (returns new scene)
#' @export
scene_set_light <- function(scene, light) {
  .Call(wrap__scene_set_light, scene, light)
}

#' Render scene to PNG bytes
#' @param scene External pointer to Scene
#' @param width Image width in pixels
#' @param height Image height in pixels
#' @param background Background color as c(r, g, b, a)
#' @return Raw vector of PNG data
#' @export
render_to_png <- function(scene, width, height, background = c(0.1, 0.1, 0.15, 1.0)) {
  .Call(wrap__render_to_png, scene, as.integer(width), as.integer(height), background)
}

#' Save PNG data to file
#' @param png_data Raw vector of PNG data
#' @param filename Output filename
#' @export
save_png <- function(png_data, filename) {
  invisible(.Call(wrap__save_png, png_data, filename))
}
